### ISSUE TITLE
Needing help getting a UDF Filesystem Driver to work

### ISSUE THREAD

**Issue by Zero3K** [mywave82/dumpiso#1]
I am having a guy work on it. Right now, he is stuck on getting it to recognize the AVDP that Windows 7/10/Linux includes when formatting a Hard Disk as it. The driver's source code is at https://github.com/reactos/reactos/tree/master/drivers/filesystems/udfs.

**Comment by mywave82** [comment]
This tool was made mostly for me as a learning/understanding how different aspects of optical filesystems works - and I used this to make cdfs/.iso/.bin/.toc (ISO9660 + UDF) into Open Cubic Player.

Please feel free to use this tool as debugging to dump information from DVD/HDD images made with UDF. I have attempted to make this tool as correct as possible with the information I found, and even tracked down a minor problem in Linux kernel implementation that was fixed.

What kind of assistance can I provide. I do not plan to do start develoment on Reactos myself, but I can provide guidance / answers to some questions I presume.

**Comment by Zero3K** [comment]
Just to figure out why the driver I linked to isn't able to recognize the AVDP in a UDF 2.01 formatted under Windows 7. It is not specifically for ReactOS, it was originally for Windows Server 2003 and up.

**Comment by Zero3K** [comment]
He needs more help.

**Comment by Zero3K** [comment]
Now he is stuck on figuring out why the driver is corrupting the VHD.

**Comment by Zero3K** [comment]
Having you dump the corrupted VHD's info will be useful to see what part(s) are corrupted. Here's the corrupted VHD compressed as a ZIP archive:

[udf2-0-1-corrupted.zip](https://github.com/mywave82/dumpiso/files/10905915/udf2-0-1-corrupted.zip)

**Comment by Zero3K** [comment]
I added you back.

**Comment by Zero3K** [comment]
Can you accept it and help him out?

**Comment by Zero3K** [comment]
He needs help fixing the issue regarding allocation amongst other ones.

**Comment by Zero3K** [comment]
Now he tells me that the driver's support for extended file entries is broken.

**Comment by Zero3K** [comment]
Please answer the questions that he commented to this issue:

https://github.com/Zero3K/udfs/issues/1

**Comment by Zero3K** [comment]
Well?
